# 服务配置
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
spec:
  ports:
    - port: $PORT
  selector:
    app: $APP_NAME
---
# 部署配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      imagePullSecrets:
        - name: bbd-docker-registry
      containers:
        - image: registry.prod.bbdops.com/front/$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
          name: $APP_NAME
          ports:
            - containerPort: $PORT
          env:
            - name: TIME_ZONE
              value: Asia/Shanghai
          resources:
            requests:
              memory: $MEMORY
              cpu: $CPU
            limits:
              memory: $MEMORY
              cpu: $CPU